<?php

namespace Tests\Unit\Repositories;

use Fronds\Lib\Exceptions\Data\FrondsEntityNotFoundException;
use Fronds\Models\User;
use Fronds\Repositories\User\UserRepository;
use Tests\TestCase;

class FrondsRepositoryTest extends TestCase
{

    /**
     * @var UserRepository
     */
    private $repository;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->repository = resolve(UserRepository::class);
    }

    public function testGenericGetByIdValid(): void
    {
        // any repository is fine
        $user = factory(User::class)->create();
        $userFromAbstractParent = $this->repository->getById($user->id);
        $this->assertEquals($user->id, $userFromAbstractParent->id);

    }

    public function testGenericGetByIdInvalid(): void
    {
        $this->expectException(FrondsEntityNotFoundException::class);
        $this->expectExceptionMessage('No entity found by that id');
        $this->repository->getById('thisisnoteveravalidid');
    }
}
